package com.beijing.geek.cms.fusheng.dao.repertory;

import com.beijing.geek.cms.fusheng.domain.repertory.PartRepertoryRecordOut;
import com.beijing.geek.cms.fusheng.domain.repertory.RepertoryQueryParam;

import java.util.List;

public interface PartRepertoryRecordOutDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_part_repertory_record_out
     *
     * @mbggenerated
     */
    int deleteById(Integer id)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_part_repertory_record_out
     *
     * @mbggenerated
     */
    int insert(PartRepertoryRecordOut record)throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_part_repertory_record_out
     *
     * @mbggenerated
     */
    PartRepertoryRecordOut selectById(Integer id)throws Exception;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_part_repertory_record_out
     *
     * @mbggenerated
     */
    int updateById(PartRepertoryRecordOut record)throws Exception;

    /**
     * 查询列表详情
     *
     * @param param
     * @return
     * @throws Exception
     */
    Integer selectOutRepertoryCountByPage(RepertoryQueryParam param) throws Exception;

    /**
     * 查询出库列表详情
     *
     * @param param
     * @return
     * @throws Exception
     */
    List<PartRepertoryRecordOut> selectOutRepertoryListByPage(RepertoryQueryParam param) throws Exception;
}