package com.beijing.geek.cms.fusheng.domain.repertory;

import java.util.Date;

public class PartRepertory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_part_repertory.id
     *
     * @mbggenerated
     */
    private Integer id;

    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_part_repertory.p_id
     *
     * @mbggenerated
     */
    private Integer pId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_part_repertory.storage_id
     *
     * @mbggenerated
     */
    private String storageId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_part_repertory.stock_num
     *
     * @mbggenerated
     */
    private Integer stockNum;

    private Integer inNum;
    private Integer outNum;
    private Double inFee;
    private Double outFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_part_repertory.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_part_repertory.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_part_repertory.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;

    private String modifierName;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_part_repertory.modified
     *
     * @mbggenerated
     */
    private Date modified;
    private String modifiedStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_part_repertory.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;
    private String pCode;
    private String pName;
    private String storageName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_part_repertory.id
     *
     * @return the value of tb_part_repertory.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_part_repertory.id
     *
     * @param id the value for tb_part_repertory.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_part_repertory.p_id
     *
     * @return the value of tb_part_repertory.p_id
     * @mbggenerated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_part_repertory.p_id
     *
     * @param pId the value for tb_part_repertory.p_id
     * @mbggenerated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_part_repertory.stock_num
     *
     * @return the value of tb_part_repertory.stock_num
     * @mbggenerated
     */
    public Integer getStockNum() {
        return stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_part_repertory.stock_num
     *
     * @param stockNum the value for tb_part_repertory.stock_num
     * @mbggenerated
     */
    public void setStockNum(Integer stockNum) {
        this.stockNum = stockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_part_repertory.creator
     *
     * @return the value of tb_part_repertory.creator
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_part_repertory.creator
     *
     * @param creator the value for tb_part_repertory.creator
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_part_repertory.created
     *
     * @return the value of tb_part_repertory.created
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_part_repertory.created
     *
     * @param created the value for tb_part_repertory.created
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_part_repertory.modifier
     *
     * @return the value of tb_part_repertory.modifier
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_part_repertory.modifier
     *
     * @param modifier the value for tb_part_repertory.modifier
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_part_repertory.modified
     *
     * @return the value of tb_part_repertory.modified
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_part_repertory.modified
     *
     * @param modified the value for tb_part_repertory.modified
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_part_repertory.deleted
     *
     * @return the value of tb_part_repertory.deleted
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_part_repertory.deleted
     *
     * @param deleted the value for tb_part_repertory.deleted
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    public String getStorageId() {
        return storageId;
    }

    public void setStorageId(String storageId) {
        this.storageId = storageId;
    }

    public String getpCode() {
        return pCode;
    }

    public void setpCode(String pCode) {
        this.pCode = pCode;
    }

    public String getpName() {
        return pName;
    }

    public void setpName(String pName) {
        this.pName = pName;
    }

    public String getStorageName() {
        return storageName;
    }

    public void setStorageName(String storageName) {
        this.storageName = storageName;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getModifiedStr() {
        return modifiedStr;
    }

    public void setModifiedStr(String modifiedStr) {
        this.modifiedStr = modifiedStr;
    }

    public String getModifierName() {
        return modifierName;
    }

    public void setModifierName(String modifierName) {
        this.modifierName = modifierName;
    }

    public Integer getInNum() {
        return inNum;
    }

    public void setInNum(Integer inNum) {
        this.inNum = inNum;
    }

    public Integer getOutNum() {
        return outNum;
    }

    public void setOutNum(Integer outNum) {
        this.outNum = outNum;
    }

    public Double getInFee() {
        return inFee;
    }

    public void setInFee(Double inFee) {
        this.inFee = inFee;
    }

    public Double getOutFee() {
        return outFee;
    }

    public void setOutFee(Double outFee) {
        this.outFee = outFee;
    }
}