package com.beijing.geek.cms.fusheng.dao.contract;

import com.beijing.geek.cms.fusheng.domain.contract.ContractQueryParam;
import com.beijing.geek.cms.fusheng.domain.contract.TbContract;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TbContractDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract
     *
     * @mbggenerated
     */
    int deleteById(@Param("id") Integer id, @Param("userId") Integer userId) throws Exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract
     *
     * @mbggenerated
     */
    int insert(TbContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract
     *
     * @mbggenerated
     */
    int insertSelective(TbContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract
     *
     * @mbggenerated
     */
    TbContract selectById(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract
     *
     * @mbggenerated
     */
    int updateByIdSelective(TbContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_contract
     *
     * @mbggenerated
     */
    int updateById(TbContract record);
    
    /**
     * zhangyongquan 2017/6/13
     * @param param
     * @return
     * @throws Exception
     */
    List<TbContract> selectContractListByPage(ContractQueryParam param) throws Exception;
    
    /**
     * zhangyongquan 2017/6/13
     * @param param
     * @return
     * @throws Exception
     */
    Integer selectContractCountByPage(ContractQueryParam param) throws Exception;
}