package com.beijing.geek.cms.fusheng.domain.contract;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class TbContract {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.id
     *
     * @mbggenerated
     */
    private Integer id = 0;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.a_code
     *
     * @mbggenerated
     */
    private String aCode = "";
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.b_code
     *
     * @mbggenerated
     */
    private String bCode = "";
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.type
     *
     * @mbggenerated
     */
    private Integer type = -1;


    private String fileIds;//文件列表，多个以逗号分割
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.c_name
     *
     * @mbggenerated
     */
    private String cName = "";
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.price
     *
     * @mbggenerated
     */
    private int cId = 0;

    private Double price = 0.0;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.is_cash_back
     *
     * @mbggenerated
     */
    private Integer isCashBack = 0;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.is_send_goods
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date cashBackDate;
    private Double cashBackPrice = 0.0;
    private String cashBackDateFormat = "";

    private Integer isSendGoods = 0;
    private Date sendGoodsDate;
    private String sendGoodsDateFormat = "";
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.is_open_invoice
     *
     * @mbggenerated
     */
    private Integer isOpenInvoice = 0;
    private Date openInvoiceDate;
    private String openInvoiceDateFormat = "";
    private String contractFile = "";
    private String contractFileId = "";

    private String note = "";
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.creator
     *
     * @mbggenerated
     */
    private Integer creator;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.created
     *
     * @mbggenerated
     */
    private Date created;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.modifier
     *
     * @mbggenerated
     */
    private Integer modifier;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.modified
     *
     * @mbggenerated
     */
    private Date modified;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column tb_contract.deleted
     *
     * @mbggenerated
     */
    private Integer deleted;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.id
     *
     * @return the value of tb_contract.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.id
     *
     * @param id the value for tb_contract.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.a_code
     *
     * @return the value of tb_contract.a_code
     * @mbggenerated
     */
    public String getaCode() {
        return aCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.a_code
     *
     * @param aCode the value for tb_contract.a_code
     * @mbggenerated
     */
    public void setaCode(String aCode) {
        this.aCode = aCode == null ? null : aCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.b_code
     *
     * @return the value of tb_contract.b_code
     * @mbggenerated
     */
    public String getbCode() {
        return bCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.b_code
     *
     * @param bCode the value for tb_contract.b_code
     * @mbggenerated
     */
    public void setbCode(String bCode) {
        this.bCode = bCode == null ? null : bCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.type
     *
     * @return the value of tb_contract.type
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.type
     *
     * @param type the value for tb_contract.type
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.c_name
     *
     * @return the value of tb_contract.c_name
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.c_name
     *
     * @param cName the value for tb_contract.c_name
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    public int getcId() {
        return cId;
    }

    public void setcId(int cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.price
     *
     * @return the value of tb_contract.price
     * @mbggenerated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.price
     *
     * @param price the value for tb_contract.price
     * @mbggenerated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.is_cash_back
     *
     * @return the value of tb_contract.is_cash_back
     * @mbggenerated
     */
    public Integer getIsCashBack() {
        return isCashBack;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.is_cash_back
     *
     * @param isCashBack the value for tb_contract.is_cash_back
     * @mbggenerated
     */
    public void setIsCashBack(Integer isCashBack) {
        this.isCashBack = isCashBack;
    }

    public Date getCashBackDate() {
        return cashBackDate;
    }

    public void setCashBackDate(Date deCashBackDate) {
        this.cashBackDate = deCashBackDate;
    }

    public Double getCashBackPrice() {
        return cashBackPrice;
    }

    public void setCashBackPrice(Double dCashBackPrice) {
        this.cashBackPrice = dCashBackPrice;
    }

    public String getCashBackDateFormat() {
        return cashBackDateFormat;
    }

    public void setCashBackDateFormat(String sCashBackDate) {
        this.cashBackDateFormat = sCashBackDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.is_send_goods
     *
     * @return the value of tb_contract.is_send_goods
     * @mbggenerated
     */
    public Integer getIsSendGoods() {
        return isSendGoods;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.is_send_goods
     *
     * @param isSendGoods the value for tb_contract.is_send_goods
     * @mbggenerated
     */
    public void setIsSendGoods(Integer isSendGoods) {
        this.isSendGoods = isSendGoods;
    }

    public Date getSendGoodsDate() {
        return sendGoodsDate;
    }

    public void setSendGoodsDate(Date deSendGoodsDate) {
        this.sendGoodsDate = deSendGoodsDate;
    }

    public String getSendGoodsDateFormat() {
        return sendGoodsDateFormat;
    }

    public void setSendGoodsDateFormat(String sSendGoodsDate) {
        this.sendGoodsDateFormat = sSendGoodsDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.is_open_invoice
     *
     * @return the value of tb_contract.is_open_invoice
     * @mbggenerated
     */
    public Integer getIsOpenInvoice() {
        return isOpenInvoice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.is_open_invoice
     *
     * @param isOpenInvoice the value for tb_contract.is_open_invoice
     * @mbggenerated
     */
    public void setIsOpenInvoice(Integer isOpenInvoice) {
        this.isOpenInvoice = isOpenInvoice;
    }

    public Date getOpenInvoiceDate() {
        return openInvoiceDate;
    }

    public void setOpenInvoiceDate(Date deOpenInvoiceDate) {
        this.openInvoiceDate = deOpenInvoiceDate;
    }

    public String getOpenInvoiceDateFormat() {
        return openInvoiceDateFormat;
    }

    public void setOpenInvoiceDateFormat(String sOpenInvoiceDate) {
        this.openInvoiceDateFormat = sOpenInvoiceDate;
    }

    public String getContractFile() {
        return contractFile;
    }

    public void setContractFile(String sContractFile) {
        this.contractFile = sContractFile;
    }

    public String getContractFileId() {
        return contractFileId;
    }

    public void setContractFileId(String sFileId) {
        this.contractFileId = sFileId;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String sNote) {
        this.note = sNote;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.creator
     *
     * @return the value of tb_contract.creator
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.creator
     *
     * @param creator the value for tb_contract.creator
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.created
     *
     * @return the value of tb_contract.created
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.created
     *
     * @param created the value for tb_contract.created
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.modifier
     *
     * @return the value of tb_contract.modifier
     * @mbggenerated
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.modifier
     *
     * @param modifier the value for tb_contract.modifier
     * @mbggenerated
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.modified
     *
     * @return the value of tb_contract.modified
     * @mbggenerated
     */
    public Date getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.modified
     *
     * @param modified the value for tb_contract.modified
     * @mbggenerated
     */
    public void setModified(Date modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column tb_contract.deleted
     *
     * @return the value of tb_contract.deleted
     * @mbggenerated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column tb_contract.deleted
     *
     * @param deleted the value for tb_contract.deleted
     * @mbggenerated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    public String getFileIds() {
        return fileIds;
    }

    public void setFileIds(String fileIds) {
        this.fileIds = fileIds;
    }
}